apiVersion: v1
kind: ReplicationController
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    app: mongodb
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-persistent
          mountPath: /data/db
      volumes:
        - name: mongodb-persistent
          # This AWS EBS volume must already exist.
          awsElasticBlockStore:
            volumeID: vol-02307bbba2f92300e
            fsType: ext4
