apiVersion: v1
kind: ReplicationController
metadata:
  name: emp-api
spec:
  replicas: 1
  selector:
    app: emp-api
  template:
    metadata:
      name: emp-api
      labels:
        app: emp-api
    spec:
      containers:
      - name: emp-api
        image: kammana/boot-api:5.0
        ports:
        - containerPort: 8080
